apiVersion: v1
kind: Pod
metadata:
  annotations:
    svc: bestman2
  name: bestman2
spec:
  hostNetwork: true
  containers:
  - command:
    - /bin/bash
    - -xec
    - |
      rm -f /etc/bestman2/conf/bestman2.rc
      ln -s /etc/bestman2conf/bestman2.rc /etc/bestman2/conf/bestman2.rc
      mkdir -p /etc/grid-security/bestman/
      if [ ! -f /etc/grid-security/bestman/bestmancert.pem ]; then
      ln -s /etc/bestman2sec/hostcert.pem /etc/grid-security/bestman/bestmancert.pem
      ln -s /etc/bestman2sec/hostkey.pem /etc/grid-security/bestman/bestmankey.pem
      fi
      chown --recursive bestman /etc/bestman2sec/
      chown --recursive bestman /etc/bestman2conf/
      echo export BESTMAN_GUMS_ENABLED=no > /etc/start.extra.sh
      rm -f /etc/grid-security/grid-mapfile
      ln -s /etc/gridmap/grid-mapfile /etc/grid-security/grid-mapfile
      grep yourproject /etc/group || groupadd -f -g 1007 yourproject
      grep yourproject /etc/passwd || useradd -g yourproject -u 1007 yourproject 
      exec bash -xe /etc/start.sh
    env:
    - name: SKIP_ENV
      value: "true"
    - name: START_WAIT_FILE
      value: /etc/grid-security/certificates/.fetch_crl_inited
    image: docker.io/pnnlhep/osg-bestman2-stable:2018-03-02
   #image: docker.io/pnnlhep/osg-bestman2:latest
    imagePullPolicy: IfNotPresent
    name: main
    ports:
    - containerPort: 8443
      name: http
      protocol: TCP
    volumeMounts:
    - mountPath: /yourproject
      name: data
    - mountPath: /etc/bestman2sec
      name: server
    - mountPath: /etc/bestman2conf
      name: config
    - mountPath: /etc/gridmap
      name: gridmap
    - mountPath: /etc/grid-security/certificates
      name: certs
  volumes:
  - hostPath:
      path: /yourproject
    name: data
  - hostPath:
      path: /export-gridmap/
    name: gridmap
  - name: server
    hostPath:
      path: /bestman2/secret
  - name: config
    hostPath:
      path: /bestman2/config
  - hostPath:
      path: /export-fetchcrl
    name: certs

